sudo: required
services:
  - docker
before_install:
  - docker build -t hooandee/carioca -f Dockerfile.dev .
  # Login to docker registries (Dockerhub + Heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - docker run -e CI=true hooandee/carioca npm run test
deploy:
  provider: script
  script:
    # Push to Dockerhub
    docker push hooandee/carioca;
  branch: master
